from . import namazButtonHandler
from . import help
from . import start
from . import surahsStart
from . import menuHandler
from . import surahHandler
from . import ramadanHandler
from . import locationHandler
from . import surahAllHandler
from . import reklamaHandler
from . import echo